### ISSUE TITLE
Things to fix in MAMBO patches III

### ISSUE THREAD

**Issue by GuillermoCallaghan** [GuillermoCallaghan/mambo#4]
The fixes are in progress in the [**`FIX_ERRORS_II`**](https://github.com/GuillermoCallaghan/mambo/tree/FIX_ERRORS_II), which is a branch based on the [**`trace_opt`**](https://github.com/beehive-lab/mambo/tree/trace_opt) branch from the official [MAMBO repository](https://github.com/beehive-lab/mambo).

_Most of the commits will be fixup later, once all the errors are corrected._

## ec01f52: [AArch64] Implementation of RAIBI (Restrictive Adaptive Indirect Branch Inlining_
* [x] `A64_INSTRUCTION` isn't specific enough, maybe `INST_SIZE` or something along these lines would be better? As long as it's defined in `scanner_a64.c`
  >Commit: fd8b83e  _[AArch64] Add the INST_SIZE macro_
* These are addressed together:
  * [x] Typo - `inliniNg`
  * [x] In the comment ```pop   reg_tmp, [sp], #16              ###``` I think should be `pop   r2, [sp], #16              ***` instead?
  * [x] `*** if rn is x0 or (blr lr)` - this also applies when `rn == x1` as it was saying before
  * [x] some of the new comments don't really seem needed, for example `// push x0, x1` for `a64_push_pair_reg(x0, x1);`
  > Commit 33fcc19: _[AArch64] Implementation of RAIBI_
* [x] instead of
    ```
    cbnz  reg_tmp, #ihlu;
    pop   reg_tmp, [sp], #16;
    br    x0
    ```
   we could have just:
    ```
    cbz branch
    ```
  > Commit d1a6f91: _[AArch64] Avoid code duplication in RAIBI routine_

  Then signal handling would just work without any changes, but I don't know what performance impact it would have.
  > **Needs to be tested for performance**

## 9fa9255: [AArch64] Fix signal handling for RAIBI

See the note above about a simple modification to allow the current signal handling to work as-is. Otherwise, the `HVC` trap needs to replace the last instruction (`BR X0`) on each possible code path before execution jumps to the target. If we replace an earlier instruction (such as the `CBZ`), we won't trap execution if the signal is delivered between that instruction and the `BR`.
  > The commit d1a6f91 implements the case where no modification to signal handling is needed.

  * [x] My suggestion would be to:
    *  wrap the code in `unlink_indirect_branch()` in a loop, so that it will replace either the first `1` or for traces with `RAIBI` `2` `BR` instruction occurrences.
    *  `restore_ihl_inst()` will need to be modified so that for traces with `RAIBI` it searches for the `2` `HVC` instances similarly to how `unlink_indirect branch()` searches for `BR`, while for other types of fragments it can continue to directly replace the instructions on which it traps.
    > This mode of handling signals is implemented in the [**`FIX_ERRORS_IIa`**](https://github.com/GuillermoCallaghan/mambo/tree/FIX_ERRORS_IIa) branch, commit 1f7a9e7: _[AArch64] Fix signal handling for RAIBI_. The [**`FIX_ERRORS_IIa`**](https://github.com/GuillermoCallaghan/mambo/tree/FIX_ERRORS_IIa) branch does not implement the d1a6f91 commit, and instead modifies `unlink_indirect_branch()` and `restore_ihl_inst()` to search and modify two instructions for indirect branches in traces when `RAIBI` is used.
  > Once the other implementation is done, will make a performance comparison

## WIP
* [ ] is it really improving performance to only update the stored prediction if it's to a trace? It's adding a larger penalty for misses
  > Will need to create one implementation where the targets are not discriminated and compare them.
  > Removing the restriction of targeting only traces is implemented in the [**`FIX_ERRORS_IIb`**](https://github.com/GuillermoCallaghan/mambo/tree/FIX_ERRORS_IIb) branch.
  > Commit: 4f2ff89 _[AArch64] Allow RAIBI to target basic blocks_
  > **With this commit MAMBO crashes when running a big application**: `./dbm  /usr/bin/gimp  -i -b '(gimp-quit 1)'`
  > The store instruction that saves the value of the `tpc` and `spc` to the _aibi slot_ seems to be corrupting the hash table and I cannot find out how/when this is happening.
  > If instead of emitting the `push x0, reg_spc, [reg_tmp]`([scanner_a64.c:687](https://github.com/GuillermoCallaghan/mambo/blob/4f2ff894e3335df5d08500b45f8b73b9c695d3d9/scanner_a64.c#L687)) instruction, I emit the `push xrz, xrz, [reg_tmp]` or if it is replaced by a `nop` instruction, the program executes just fine.

## TODO

Once it is decided which commits are taken, the following things should be corrected:

* [x] This comment `// ldp reg_tmp, x0, [reg_tmp]` in RAIBI should be `// ldp x0, reg_tmp, [reg_tmp]` 
  * It is correct in the top comment of the `ihlu`
* [x] In the top comment in the `ihlu` the line `go_to_dispatcher: mov   x0, x1` should be `// mov x1, reg_spc`
* [x] The comment `// push x0, reg_tmp, [reg_tmp]` should be `// push x0, reg_spc, [reg_tmp]`
  * [x] In the top comment in the `ihlu` it is also wrong. It is `stp   x0, x1, [reg_tmp]` and should be `stp   x0, x1, [reg_spc], [reg_tmp]`
  * [x] Also, decide to use `stp` or `push`
